### ISSUE TITLE
Error in Safari 18

### ISSUE THREAD

**Issue by axiel7** [katagaki/Unagent#23] opened 2024-06-18 10:28 UTC
I know Safari 18 is still in beta, but the extension doesn't load with the error `Unable to parse declarativeNetRequest rules because of an unexpected error.`

<img width="535" alt="Screenshot 2024-06-18 at 12 27 58" src="https://github.com/katagaki/Unagent/assets/12379835/bd4b0e8d-8ce3-4cb0-a391-6983c82e971b">

**Comment by katagaki** [comment] 2024-06-30 22:38
Hi @axiel7 !

Just an update on this issue, it seems like in iOS 18 Developer Beta 2, the extension is not working at all, with the same error you provided shown in Settings > Apps > Safari > Extensions > Unagent.
If the issue is not resolved in iOS 18 Developer Beta 3, I will reach out to Apple to ask for support.

**Comment by katagaki** [comment] 2024-08-06 04:03
This seems to be caused by commit https://github.com/katagaki/Unagent/commit/bc1c88167bfe78d91182b64cea1bf830033d6bc7 .

The resource type list has been tweaked in accordance to [Apple's documentation](https://developer.apple.com/documentation/safariservices/blocking-content-with-your-safari-web-extension):

> Safari supports main_frame, sub_frame, stylesheet, script, image, font, xmlhttprequest, ping, media, websocket, and other.

It should be fixed when building commit https://github.com/katagaki/Unagent/commit/a976976ac176ef54a52c3b30b902ced25b0dfede .

This fix will be released in Unagent 1.3.

**Closed by katagaki** 2024-08-06 04:03 UTC
Labels: bug
